### ISSUE TITLE
what does `RTS` stand for ?

### ISSUE THREAD

**Issue by xieyuheng** [thautwarm/idris-cam#1]

**Comment by thautwarm** [comment]
runtime system

**Comment by thautwarm** [comment]
You have already written lots of these things @xieyuheng

**Comment by xieyuheng** [comment]
thanks for explaining.
"common abstract machine" `.cam` is a backend of idirs and julia ?
it is magical.
where can I learn more about `.cam` ?

**Comment by xieyuheng** [comment]
`.cam` works like `.wasm` ?

**Comment by thautwarm** [comment]
@xieyuheng Common abstract machine is a very simple abstract machine. Instead of executing bytecodes or wordcodes, abstract machine could interpret instructions that're formed in hierarchical data types(or abstract data types).
You might want to Google abstract machine or operational semantics.

**Comment by thautwarm** [comment]
I've been pondering something like common abstract machine for years, and then I learned LLVM and type checkers, however it turns out that it's infeasible for an individual to end the situation that programming langs are too separate from each other.
Since that, I decide to work with some projects that've already made unprecedented progress for my goals, where idris and julia are both that sort of projects.

**Comment by xieyuheng** [comment]
I found this :: https://en.wikipedia.org/wiki/Categorical_abstract_machine
so cool! 
加油

**Comment by thautwarm** [comment]
谢谢！
This CAM is not that CAM though...
